[package]
name = "physics-test"
version = "0.1.0"
edition = "2021"
publish = false
description.workspace = true
repository.workspace = true
license.workspace = true

[features]
tracy = ["concerto/tracy"]

[[bin]]
name = "physics-test"
path = "src/main.rs"

[dependencies]
concerto = { path = "../.." }
concerto-color = { path = "../../crates/color" }
glam = "0.30.1"
env_logger = "0.11.8"
