//! `AssetId` constants for every file in `content-manifest.txt`, generated by
//! `build.rs`.
#![allow(dead_code)]

use concerto::{asset_id, foundation::assets::AssetId};

include!(concat!(env!("OUT_DIR"), "/content.rs"));
