[package]
name = "concerto-ui-egui"
version.workspace = true
edition = "2021"
description.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
concerto-app.workspace = true
concerto-ecs.workspace = true
concerto-render.workspace = true
concerto-window.workspace = true
egui = { version = "0.31.1", default-features = false }
egui-winit = { version = "0.31.1", default-features = false }
egui-wgpu = { version = "0.31.1", default-features = false }
