[package]
name = "concerto-gameplay"
version.workspace = true
edition = "2024"
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
concerto-app.workspace = true
concerto-director.workspace = true
concerto-foundation.workspace = true
concerto-render.workspace = true
concerto-window.workspace = true
concerto-ecs.workspace = true
glam = { version = "0.30.1" }