[package]
name = "concerto-import"
version.workspace = true
edition = "2021"
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
concerto-asset-import.workspace = true
concerto-foundation.workspace = true
concerto-gltf.workspace = true
concerto-obj.workspace = true
concerto-render.workspace = true
anyhow = "1.0.97"
env_logger = "0.11.6"
log = "0.4.27"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tempfile = "3"

[dev-dependencies]
concerto-scene.workspace = true
concerto-mesh.workspace = true
concerto-ecs.workspace = true
serde_json = "1.0"
bincode = "1.3"
pollster = "0.4.0"
