[package]
name = "concerto-director"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
concerto-app = { path = "../app" }
concerto-foundation = { path = "../foundation" }
concerto-render = { path = "../render" }
concerto-ecs = { path = "../ecs" }
glam = { version = "0.30.1" }
serde = { version = "1", features = ["derive"] }
log = "0.4.27"
