[package]
name = "concerto-obj-loader"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
concerto-app = { path = "../app" }
concerto-asset-import = { path = "../asset-import" }
concerto-color = { path = "../color" }
concerto-foundation = { path = "../foundation" }
concerto-mesh = { path = "../mesh" }
concerto-ecs = { path = "../ecs" }
concerto-render = { path = "../render" }
concerto-scene = { path = "../scene" }
tobj = { version = "4.0.3", default-features = false }
anyhow = "1.0.97"
bincode = "1.3"
glam = { version = "0.30.1" }
serde = { version = "1", features = ["derive"] }

[dependencies.image]
version = "0.25.5"
default-features = true
